#!/usr/bin/env python3
"""Curate ~1000 uninformative single-token contexts for ReferenceBank.build_mu (SPEC §2.2).

Deterministic: same (label, seed, N, tokenizer, seed-list) -> byte-identical output. The
header carries ONLY stable provenance (label + tokenizer sha256 + N + seed + script version)
so re-running with a different repo mirror of the SAME tokenizer yields an identical file --
that is the determinism/fidelity check (`git diff --exit-code`). No code_sha, no timestamp:
volatile provenance belongs in the commit message, not the artifact.

engineering-notes lesson #3: a data fixture no CI test reads is unverified by construction.
This script GENERATES the fixture; tests/test_data_integrity.py GUARDS its shape. Both.

The pilot tokenizer (Llama-3.2-1B) is gated and lives on the owner's Track B machine. The
single-token filter (re-encode <= 2 tokens, i.e. BOS + the token) is only valid against that
exact tokenizer, so the file is canonical only when built with it; Track B re-runs and
confirms `git diff` is empty.
"""
import argparse
import hashlib
import json
import sys
from random import Random

SCRIPT_VERSION = "1.0"


def tokenizer_sha256(tok) -> str:
    """Stable fingerprint of the tokenizer's core (vocab + merges), mirror-independent."""
    try:
        repr_str = tok.backend_tokenizer.to_str()        # fast tokenizer: full tokenizer.json
    except Exception:
        repr_str = json.dumps(tok.get_vocab(), sort_keys=True)
    return hashlib.sha256(repr_str.encode("utf-8")).hexdigest()


def read_seed_list(path: str) -> list[str]:
    with open(path, encoding="utf-8") as fh:
        return [ln.strip() for ln in fh if ln.strip() and not ln.startswith("#")]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tokenizer-id", default="meta-llama/Llama-3.2-1B",
                    help="HF repo to load the tokenizer from (official, or an open mirror).")
    ap.add_argument("--label", default="Llama-3.2",
                    help="Canonical tokenizer-family label for the header (mirror-invariant).")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--n", type=int, default=1000)
    ap.add_argument("--seed-list", default="data/prompts/uninformative.seed.txt")
    ap.add_argument("--out", default="data/prompts/uninformative.txt")
    args = ap.parse_args()

    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(args.tokenizer_id, trust_remote_code=False)

    specials = set(tok.all_special_ids)
    added = set(getattr(tok, "added_tokens_decoder", {}).keys())

    # Map each clean surface form to the FIRST vocab id that produces it (stable, dedup over
    # the stripped surface: distinct ids decoding to the same prompt collapse to one).
    surface_to_id: dict[str, int] = {}
    for tid in range(len(tok)):
        if tid in specials or tid in added:
            continue
        s = tok.decode([tid]).strip()                     # strip BPE space prefix (e.g. 'Ġ')
        if not s.isalnum():                               # alphanumeric surface only
            continue
        if len(tok(s, add_special_tokens=True)["input_ids"]) > 2:   # BOS + token at most
            continue
        surface_to_id.setdefault(s, tid)

    surfaces = sorted(surface_to_id, key=lambda s: surface_to_id[s])   # stable order by id
    Random(args.seed).shuffle(surfaces)                               # seeded deterministic sample

    chosen: list[str] = list(dict.fromkeys(read_seed_list(args.seed_list)))   # seed list first
    for s in surfaces:
        if len(chosen) >= args.n:
            break
        if s not in chosen:
            chosen.append(s)
    chosen = chosen[: args.n]

    header = [
        f"# uninformative.txt - GENERATED by scripts/build_uninformative.py v{SCRIPT_VERSION}. "
        "DO NOT HAND-EDIT.",
        f"# model={args.label} seed={args.seed} N={len(chosen)}",
        f"# tokenizer_sha256={tokenizer_sha256(tok)} tokenizer_len={len(tok)}",
    ]
    with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(header) + "\n")
        fh.write("\n".join(chosen) + "\n")

    print(f"wrote {len(chosen)} contexts -> {args.out} "
          f"(from {len(surfaces)} vocab candidates, tokenizer={args.tokenizer_id})")
    if len(chosen) < args.n:
        print(f"WARNING: only {len(chosen)} < N={args.n}; widen the filter or vocab.",
              file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
